services:
  db:
    image: postgres:15
    container_name: gallery_app_db
    restart: always
    environment:
      POSTGRES_DB: gallery_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build: .
    container_name: gallery_app
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8001 myproject.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8002:8001"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5433/gallery_app_db
    networks:
      - django_network
      
volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge